### ISSUE TITLE
Add an error-reporting system

### ISSUE THREAD

**Issue by adamhutchings** [jabacat/jccc#10]
For example, warnings print in yellow, errors in red, general messages in white, etc.

**Comment by JakeRoggenbuck** [comment]
Oh yay! I can do this after I do #12

**Comment by JakeRoggenbuck** [comment]
Could we use https://github.com/JakeRoggenbuck/termcolor-c?

**Comment by JakeRoggenbuck** [comment]
Wait never mind, I just saw that you've already done it well
